application: arthur-wynn
version: 8
runtime: python
api_version: 1

handlers:
- url: /microapp/microapp.xml
  static_files: microapp/microapp.xml
  upload: microapp/microapp.xml

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: arthurwynn/pathmapping.py
